<?php namespace Gco\KongApiClient\Domain\Route;

use Gco\KongApiClient\Repository\Contract\RouteRepositoryContract;

class Route
{
    private $id;

    private $name;

    private $configuration;

    private $routeRepository;

    /**
     * Route constructor.
     * @param Configuration $configuration
     * @param string|null $id is auto generated by kong, do not provide your custom id
     * @param string|null $name
     */
    public function __construct(Configuration $configuration, string $id = null, string $name = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->configuration = $configuration;
        $this->routeRepository = app(RouteRepositoryContract::class);
    }

    public function createAndAssociateToService($serviceId): array
    {
        $routeCreatedData = $this->routeRepository->create(
            $serviceId,
            $this->configuration->toArray()
        );
        $this->id = $routeCreatedData['id'];
        $this->name = $routeCreatedData['name'];
        return $routeCreatedData;
    }

    public function delete():bool
    {
        $this->routeRepository->delete($this->identity());
        return true;
    }

    private function identity():string
    {
        return isset($this->id) ? $this->id : $this->name;
    }

}